### ISSUE TITLE
firebase_messaging version

### ISSUE THREAD

**Issue by PFP887** [mwaylabs/flutter-apns#110]
You have updated the version of firebase_messaging but no version has been pushed. Can you please make a new version of your package.

**Comment by jaween** [comment]
+1 
I need updated Firebase dependencies due to other reasons, but I am also relying on this package.

In the meantime, until a new package is pushed you can point your `pubspec.yaml` dependency at GitHub instead of at pub.

Replace :
`flutter_apns: ^1.6.0`

With:
```
flutter_apns:
  git:
    url: https://github.com/mwaylabs/flutter-apns/
    ref: master
    path: flutter_apns
```
